# -*- coding: utf-8 -*-
"""Retail_Business_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cprMV2XaQjhY72sKK4yTRGr7NPjRQh6E

# Retail Business Performance & Profitability Analysis

## Objective

Analyze retail transactional data to identify:
- Profit-draining categories and sub-categories
- Regional profitability
- Discount impact on profit
- Seasonal product behavior
- Fulfillment-time and profitability patterns

## Tools

Python, Pandas, NumPy, Matplotlib, Seaborn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Verify the original file"""

import os

print(os.listdir('/'))

"""Load Orders.csv"""

import pandas as pd

df = pd.read_csv('/Orders.csv')

df.head()

df.shape

"""STEP 1 — Check Your Columns"""

df.columns.tolist()

"""STEP 2 — Convert the Date Columns"""

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

df[['Order Date', 'Ship Date']].head()

"""STEP 3 — Check the Date Data Types"""

df[['Order Date', 'Ship Date']].dtypes

"""STEP 4 — Create Shipping_Days"""

df['Shipping_Days'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

df[['Order Date', 'Ship Date', 'Shipping_Days']].head(10)

"""STEP 5 — Check Shipping Days"""

df['Shipping_Days'].describe()

"""STEP 6 - Create the Season column"""

df['Season'] = df['Order Date'].dt.month.map({
    12: 'Winter',
    1: 'Winter',
    2: 'Winter',
    3: 'Spring',
    4: 'Spring',
    5: 'Spring',
    6: 'Summer',
    7: 'Summer',
    8: 'Summer',
    9: 'Autumn',
    10: 'Autumn',
    11: 'Autumn'
})

df[['Order Date', 'Season']].head(10)

"""STEP 7 — Create Profit_Margin"""

df['Profit_Margin'] = np.where(
    df['Sales'] == 0,
    0,
    df['Profit'] / df['Sales']
)

# Check the calculation
df[['Sales', 'Profit', 'Profit_Margin']].head(10)

"""STEP 8 — Check Your Final Dataset"""

df.shape

df[['Shipping_Days', 'Season', 'Profit_Margin']].head(10)

df.isnull().sum()

"""STEP 9 — Category Profitability Analysis"""

# Which category generates the most sales and profit?
category_analysis = df.groupby('Category').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

category_analysis['Profit_Margin_%'] = (
    category_analysis['Total_Profit'] /
    category_analysis['Total_Sales'] * 100
)

category_analysis

"""STEP 10 — Sort by Profit"""

category_analysis.sort_values(
    'Total_Profit',
    ascending=False
)

"""STEP 11 — Create Your First Chart"""

# Which category contributes the most profit?
plt.figure(figsize=(8, 5))

sns.barplot(
    data=category_analysis,
    x='Category',
    y='Total_Profit'
)

plt.title('Total Profit by Category')
plt.xlabel('Category')
plt.ylabel('Total Profit')
plt.xticks(rotation=0)

plt.show()

"""STEP 12 — Sales vs Profit"""

category_melted = category_analysis.melt(
    id_vars='Category',
    value_vars=['Total_Sales', 'Total_Profit'],
    var_name='Metric',
    value_name='Amount'
)

plt.figure(figsize=(9, 5))

sns.barplot(
    data=category_melted,
    x='Category',
    y='Amount',
    hue='Metric'
)

plt.title('Sales vs Profit by Category')
plt.xlabel('Category')
plt.ylabel('Amount')

plt.show()

"""STEP 13 — Analyze Sub-Categories"""

subcategory_analysis = df.groupby(
    ['Category', 'Sub-Category']
).agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

subcategory_analysis['Profit_Margin_%'] = (
    subcategory_analysis['Total_Profit'] /
    subcategory_analysis['Total_Sales'] * 100
)

subcategory_analysis

"""STEP 14 — Find the Profit Drainers"""

subcategory_analysis.sort_values(
    'Total_Profit',
    ascending=True
)

"""STEP 15 — Visualize Sub-Category Profitability"""

plt.figure(figsize=(12, 7))

sns.barplot(
    data=subcategory_analysis.sort_values('Total_Profit'),
    x='Total_Profit',
    y='Sub-Category'
)

plt.title('Profitability by Sub-Category')
plt.xlabel('Total Profit')
plt.ylabel('Sub-Category')

plt.show()

"""STEP 16 — Regional Performance"""

region_analysis = df.groupby('Region').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

region_analysis['Profit_Margin_%'] = (
    region_analysis['Total_Profit'] /
    region_analysis['Total_Sales'] * 100
)

region_analysis

region_analysis.sort_values(
    'Total_Profit',
    ascending=False
)

"""STEP 17 — Visualize Regional Profit"""

plt.figure(figsize=(8, 5))

sns.barplot(
    data=region_analysis.sort_values('Total_Profit'),
    x='Total_Profit',
    y='Region'
)

plt.title('Total Profit by Region')
plt.xlabel('Total Profit')
plt.ylabel('Region')

plt.show()

"""STEP 18 — Regional Sales vs Profit"""

region_melted = region_analysis.melt(
    id_vars='Region',
    value_vars=['Total_Sales', 'Total_Profit'],
    var_name='Metric',
    value_name='Amount'
)

plt.figure(figsize=(9, 5))

sns.barplot(
    data=region_melted,
    x='Region',
    y='Amount',
    hue='Metric'
)

plt.title('Sales vs Profit by Region')
plt.xlabel('Region')
plt.ylabel('Amount')

plt.show()

"""STEP 19 — Discount vs Profit"""

#Does profitability decrease as discount levels increase?
discount_analysis = df.groupby('Discount').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

discount_analysis['Profit_Margin_%'] = (
    discount_analysis['Total_Profit'] /
    discount_analysis['Total_Sales'] * 100
)

discount_analysis

#Sort by discount
discount_analysis.sort_values('Discount')

"""STEP 20 — Visualize Discount vs Profit"""

plt.figure(figsize=(9, 5))

sns.barplot(
    data=discount_analysis,
    x='Discount',
    y='Total_Profit'
)

plt.title('Total Profit by Discount Level')
plt.xlabel('Discount')
plt.ylabel('Total Profit')

plt.show()

"""STEP 21 — Seasonal Performance"""

#Which season generates the highest sales and profit?
season_analysis = df.groupby('Season').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

season_analysis['Profit_Margin_%'] = (
    season_analysis['Total_Profit'] /
    season_analysis['Total_Sales'] * 100
)

season_analysis

#Sort by profit
season_analysis.sort_values(
    'Total_Profit',
    ascending=False
)

"""STEP 22 — Visualize Seasonal Profit"""

plt.figure(figsize=(8, 5))

sns.barplot(
    data=season_analysis.sort_values('Total_Profit'),
    x='Season',
    y='Total_Profit'
)

plt.title('Total Profit by Season')
plt.xlabel('Season')
plt.ylabel('Total Profit')

plt.show()

"""STEP 23 — Seasonal Sales vs Profit"""

season_melted = season_analysis.melt(
    id_vars='Season',
    value_vars=['Total_Sales', 'Total_Profit'],
    var_name='Metric',
    value_name='Amount'
)

plt.figure(figsize=(9, 5))

sns.barplot(
    data=season_melted,
    x='Season',
    y='Amount',
    hue='Metric'
)

plt.title('Sales vs Profit by Season')
plt.xlabel('Season')
plt.ylabel('Amount')

plt.show()

"""STEP 24 — Shipping Days vs Profit Correlation"""

correlation = df['Shipping_Days'].corr(df['Profit'])

print("Correlation between Shipping Days and Profit:", round(correlation, 4))

"""STEP 25 — Visualize Shipping Days vs Profit"""

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=df,
    x='Shipping_Days',
    y='Profit',
    alpha=0.4
)

plt.title('Shipping Days vs Profit')
plt.xlabel('Shipping Days')
plt.ylabel('Profit')

plt.show()

"""STEP 26 — Add a Trend Line"""

plt.figure(figsize=(9, 6))

sns.regplot(
    data=df,
    x='Shipping_Days',
    y='Profit',
    scatter_kws={'alpha': 0.3},
    line_kws={}
)

plt.title('Relationship Between Shipping Days and Profit')
plt.xlabel('Shipping Days')
plt.ylabel('Profit')

plt.show()

"""STEP 27 — Saving Python Analysis Dataset"""

df.to_csv('Retail_Python_Cleaned.csv', index=False)

import os

os.path.exists('/content/Retail_Python_Cleaned.csv')

"""STEP 28 — Top & Bottom Products"""

#Find the 10 most profitable products
top_products = df.groupby(
    ['Product Name', 'Category', 'Sub-Category']
).agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Total_Quantity=('Quantity', 'sum')
).reset_index()

top_products['Profit_Margin_%'] = (
    top_products['Total_Profit'] /
    top_products['Total_Sales'] * 100
)

top_10 = top_products.sort_values(
    'Total_Profit',
    ascending=False
).head(10)

top_10

"""STEP 28 — Find the 10 Worst Products"""

bottom_10 = top_products.sort_values(
    'Total_Profit',
    ascending=True
).head(10)

bottom_10

"""STEP 30 — Visualize the Bottom 10"""

plt.figure(figsize=(10, 7))

sns.barplot(
    data=bottom_10,
    x='Total_Profit',
    y='Product Name'
)

plt.title('10 Least Profitable Products')
plt.xlabel('Total Profit')
plt.ylabel('Product')

plt.show()

"""STEP 30 — Investigate the Loss-Making Products"""

loss_products = df[df['Profit'] < 0].groupby(
    ['Category', 'Sub-Category']
).agg(
    Loss_Making_Orders=('Order ID', 'count'),
    Total_Sales=('Sales', 'sum'),
    Total_Loss=('Profit', 'sum'),
    Average_Discount=('Discount', 'mean')
).reset_index()

loss_products.sort_values(
    'Total_Loss',
    ascending=True
)

"""STEP 31 — Overall Business KPIs"""

kpis = {
    'Total Sales': df['Sales'].sum(),
    'Total Profit': df['Profit'].sum(),
    'Total Orders': df['Order ID'].nunique(),
    'Total Customers': df['Customer ID'].nunique(),
    'Total Units Sold': df['Quantity'].sum(),
    'Overall Profit Margin %': (
        df['Profit'].sum() / df['Sales'].sum()
    ) * 100,
    'Average Discount %': df['Discount'].mean() * 100,
    'Average Shipping Days': df['Shipping_Days'].mean()
}

kpis

"""STEP 32 — Make the KPI Output in easy language"""

kpi_table = pd.DataFrame(
    list(kpis.items()),
    columns=['KPI', 'Value']
)

kpi_table

"""STEP 33 — Monthly Sales & Profit Trend"""

monthly_analysis = df.groupby(
    df['Order Date'].dt.to_period('M')
).agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum')
).reset_index()

monthly_analysis['Month'] = (
    monthly_analysis['Order Date']
    .astype(str)
)

monthly_analysis

plt.figure(figsize=(14, 6))

plt.plot(
    monthly_analysis['Month'],
    monthly_analysis['Total_Sales'],
    label='Sales'
)

plt.plot(
    monthly_analysis['Month'],
    monthly_analysis['Total_Profit'],
    label='Profit'
)

plt.title('Monthly Sales and Profit Trend')
plt.xlabel('Month')
plt.ylabel('Amount')
plt.xticks(rotation=45)
plt.legend()

plt.show()

df.to_csv(
    'Retail_Python_Cleaned.csv',
    index=False
)

import os

print(os.path.exists('/content/Retail_Python_Cleaned.csv'))